
project_id = "jrwyptpespjvjisrwnbh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[edge_runtime]
enabled = true

[analytics]
enabled = false
port = 54330

[functions.fitbit-oauth]
verify_jwt = false

[functions.fitbit-callback]
verify_jwt = false
