services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8080
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
