services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_FITBIT_CLIENT_ID=${VITE_FITBIT_CLIENT_ID}
      - VITE_SITE_URL=${VITE_SITE_URL}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
