[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  CI = "false"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://c97d7ea5.mobsted.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; connect-src 'self' https: https://c97d7ea5.mobsted.com; font-src 'self' data: https://fonts.gstatic.com; media-src 'self'; object-src 'none'; frame-src 'self' https: https://accounts.fitbit.com; worker-src 'self'; frame-ancestors 'self' https://accounts.fitbit.com https://c97d7ea5.mobsted.com; base-uri 'self'; form-action 'self';"
